# Generated by Django 4.2 on 2024-10-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default='https://f004.backblazeb2.com/b2api/v1/b2_download_file_by_id?fileId=4_zb2b6343f2ed711629a2d0415_f106c769b544871d7_d20241010_m094226_c004_v0402013_t0018_u01728553346146', max_length=1000, null=True),
        ),
    ]
